"""Transport-independent Kai Workshop domain and persistence foundations.

The current production service seeds this state and shadow-records accepted
inbound text, successful assistant results, and delivery observations. Existing
Telegram routing, histories, and responses remain authoritative until replay
and parity evidence supports an explicit cutover.
"""

from kai.workshop.artifacts import (
    ArtifactMessageNotFoundError,
    ArtifactStorageBoundaryError,
    InboundArtifact,
    record_inbound_artifact,
)
from kai.workshop.authorization import CanonicalChannelAuthorizer
from kai.workshop.client_api import (
    WorkshopClientAuthenticator,
    register_workshop_enrollment_routes,
    register_workshop_read_routes,
)
from kai.workshop.client_sessions import (
    AuthenticatedWorkshopClientSession,
    ClientDeviceUnavailableError,
    EnrollmentGrantUnavailableError,
    IssuedWorkshopClientSession,
    IssuedWorkshopEnrollmentGrant,
    RedeemedWorkshopClient,
    TrackedClientDevice,
    WorkshopBearerSessionAuthenticator,
    WorkshopClientEnrollmentManager,
    WorkshopClientSessionManager,
)
from kai.workshop.delivery_outbox import (
    DeliveryClaim,
    DeliveryOutboxError,
    DeliveryRecoveryResult,
    DeliveryRequest,
    DeliveryRequestConflictError,
    DeliveryRequestResult,
    DeliveryState,
    DeliveryTargetNotFoundError,
    StaleDeliveryLeaseError,
    WorkshopDeliveryOutbox,
)
from kai.workshop.domain import (
    AgentId,
    ArtifactId,
    ChannelAgentId,
    ChannelBindingId,
    ChannelId,
    ChannelMembershipId,
    ClientSessionId,
    DeliveryAttemptId,
    DeliveryId,
    DeviceId,
    EnrollmentGrantId,
    EventEnvelope,
    EventId,
    ExternalIdentityId,
    MessageId,
    PrincipalId,
    WorkshopEventType,
    WorkshopId,
    WorkshopMembershipId,
)
from kai.workshop.store import (
    AppendResult,
    EventIntegrityError,
    IdempotencyConflictError,
    Projection,
    ProjectionCheckpoint,
    StoredEvent,
    WorkshopEventStore,
)
from kai.workshop.timeline import (
    ChannelTimelineAuthorizer,
    TimelineAccessDeniedError,
    TimelineCursorError,
    TimelineMessage,
    TimelinePage,
    read_channel_timeline,
)

__all__ = [
    "AgentId",
    "AppendResult",
    "ArtifactId",
    "ArtifactMessageNotFoundError",
    "ArtifactStorageBoundaryError",
    "AuthenticatedWorkshopClientSession",
    "CanonicalChannelAuthorizer",
    "ChannelAgentId",
    "ChannelBindingId",
    "ChannelId",
    "ChannelMembershipId",
    "ChannelTimelineAuthorizer",
    "ClientDeviceUnavailableError",
    "ClientSessionId",
    "DeliveryAttemptId",
    "DeliveryClaim",
    "DeliveryId",
    "DeliveryOutboxError",
    "DeliveryRecoveryResult",
    "DeliveryRequest",
    "DeliveryRequestConflictError",
    "DeliveryRequestResult",
    "DeliveryState",
    "DeliveryTargetNotFoundError",
    "DeviceId",
    "EnrollmentGrantId",
    "EnrollmentGrantUnavailableError",
    "EventEnvelope",
    "EventId",
    "EventIntegrityError",
    "ExternalIdentityId",
    "IdempotencyConflictError",
    "InboundArtifact",
    "IssuedWorkshopClientSession",
    "IssuedWorkshopEnrollmentGrant",
    "MessageId",
    "PrincipalId",
    "Projection",
    "ProjectionCheckpoint",
    "RedeemedWorkshopClient",
    "StaleDeliveryLeaseError",
    "StoredEvent",
    "TimelineAccessDeniedError",
    "TimelineCursorError",
    "TimelineMessage",
    "TimelinePage",
    "TrackedClientDevice",
    "WorkshopBearerSessionAuthenticator",
    "WorkshopClientAuthenticator",
    "WorkshopClientEnrollmentManager",
    "WorkshopClientSessionManager",
    "WorkshopDeliveryOutbox",
    "WorkshopEventStore",
    "WorkshopEventType",
    "WorkshopId",
    "WorkshopMembershipId",
    "read_channel_timeline",
    "record_inbound_artifact",
    "register_workshop_enrollment_routes",
    "register_workshop_read_routes",
]
